export const BOT_PLAY_CARD_DELAY = 300;
export const BOT_PLACE_BID_DELAY = 400;
export const BOT_MAKE_CHIEN_DELAY = 3000;

export const SERVER_AWARD_BID_DELAY = 2000;
export const SERVER_BIDDING_FAILED_DELAY = 2000;
export const SERVER_AWARD_TRICK_DELAY = 1000;
export const SERVER_AWARD_ROUND_DELAY = 1000;
