export const BOT_PLAY_CARD_DELAY = 20;
export const BOT_PLACE_BID_DELAY = 20;
export const BOT_MAKE_CHIEN_DELAY = 100;

export const SERVER_AWARD_BID_DELAY = 100;
export const SERVER_BIDDING_FAILED_DELAY = 100;
export const SERVER_AWARD_TRICK_DELAY = 100;
export const SERVER_AWARD_ROUND_DELAY = 100;
